version: '3.9'
services:
  web:
    env_file:
      - .env
    container_name: ${WEB_HOST}
    hostname: ${WEB_HOST}
    build: ./app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      FLASK_RUN_HOST: 0.0.0.0
      TEMPLATES_AUTO_RELOAD: 'True'
      FLASK_ENV: development
    ports: 
      - '8000:5000'
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./app:/app
    networks:
      - default
  database:
    image: mongo:latest
    env_file:
      - .env
    container_name: ${MONGO_HOST}
    hostname: ${MONGO_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ${MONGO_HOST_DATA}/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${MONGO_HOST_DATA}/mongo-volume:/data/db
      - ${MONGO_HOST_DATA}/mongo-volume/log:/var/log/mongodb/
    ports:
      - '27017-27019:27017-27019'
    networks:
      - default
  mongo-express:
    image: mongo-express
    container_name: ${MONGO_EXP_HOST}
    hostname: ${MONGO_EXP_HOST}
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@database:27017/
  redis:
    image: redis
    container_name: ${REDIS_HOST}
    hostname: ${REDIS_HOST}
    ports:
      - 6379:6379
  worker:
      image: worker
      restart: always
      container_name: ${WORKER_HOST}
      hostname: ${WORKER_HOST}
      build:
        context: ./worker
        dockerfile: Dockerfile
      depends_on:
        - redis
volumes:
  persistent: